//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programistek {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Programistek.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Jeżeli chcemy, by użytkownik wprowadził tekst może użyć funkcję &quot;Input&quot;. Przykładowo :.
        /// </summary>
        internal static string InputPython {
            get {
                return ResourceManager.GetString("InputPython", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu #include &lt;iostram&gt;
        ///int main()
        ///{
        ///int ile;
        ///std::cout &lt;&lt; &quot;Ile gwiazdek dasz Programistkowi?&quot;;
        ///std::cin &gt;&gt; ile;
        ///while(ile)
        ///{ std::cout &lt;&lt; &quot;*&quot;; 
        ///   ile = ile - 1; }
        ///}
        ///Jeżeli podamy liczbę 3 wtedy, dzięki pętli wyświetlą nam się 3 gwaizdki, tak jak pokazuje nam to Programistek.
        ///.
        /// </summary>
        internal static string KodWhileCplus {
            get {
                return ResourceManager.GetString("KodWhileCplus", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Instrukcja warunkowa if.
        /// </summary>
        internal static string StringIfCplus {
            get {
                return ResourceManager.GetString("StringIfCplus", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Instrukcja sterująca while polega na tym, że pewna instrukcja lub blok instrukcji będzie wykonywała się dopóki warunek nie zostanie spełniony. Jego budowa wygląda tak:  
        ///while(warunek) instrukcja; 
        ///.
        /// </summary>
        internal static string StringWhileCplus {
            get {
                return ResourceManager.GetString("StringWhileCplus", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do stworzenia zmiennych w języku Python potrzebujesz nazwę zmiennej, do której podaje sie wartość.
        /// </summary>
        internal static string ZmiennePython {
            get {
                return ResourceManager.GetString("ZmiennePython", resourceCulture);
            }
        }
    }
}
